# Generated by Django 6.0.3 on 2026-04-04 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biomarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Biomarker Name')),
            ],
        ),
        migrations.CreateModel(
            name='Electrode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Electrode Label')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Electrode Material')),
                ('biomarker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='electrodes', to='measurements.biomarker')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(choices=[('EIS', 'Electrochemical Impedance Spectroscopy'), ('CV', 'Cyclic Voltammetry'), ('DPV', 'Differential Pulse Voltammetry'), ('SWV', 'Square Wave Voltammetry'), ('CA', 'Chronoamperometry'), ('HER', 'Hydrogen Evolution Reaction'), ('OER', 'Oxygen Evolution Reaction'), ('ORR', 'Oxygen Reduction Reaction'), ('Other', 'Other')], max_length=5)),
                ('date_performed', models.DateField(verbose_name='Measurement Date')),
                ('raw_file', models.FileField(upload_to='uploads/raw/%Y/%m/', verbose_name='Raw Data .DTA')),
                ('csv_file', models.FileField(blank=True, null=True, upload_to='uploads/csv/%Y/%m/', verbose_name='Processed Data .CSV')),
                ('peak_potelntial', models.FloatField(blank=True, null=True, verbose_name='Peak Potential (V)')),
                ('peak_current', models.FloatField(blank=True, null=True, verbose_name='Peak Current (A)')),
                ('lod', models.FloatField(blank=True, null=True, verbose_name='Limit of Detection (LOD)')),
                ('loq', models.FloatField(blank=True, null=True, verbose_name='Limit of Quantification (LOQ)')),
                ('electrode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='measurements.electrode')),
            ],
            options={
                'ordering': ['-date_performed'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Project Name')),
                ('description', models.TextField(blank=True, verbose_name='Project Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('members', models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='biomarker',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biomarkers', to='measurements.project'),
        ),
    ]
